mode: "dev"

server:
  port: 6306

logger:
  level: "debug"
  filename: "./log/bluespot.log"
  max_size: 100 # 单文件最大体积，单位 MB
  max_age: 30 # 历史日志最大保留天数，单位 day
  max_backups: 5

database:
  mysql:
    addr: "localhost:3306"
    user: "root"
    password: "123456"
    db_name: "bluespot"

jwt:
  secret: "foobarorange"
  access_expires_in: "2h"
  refresh_expires_in: "72h"

auth:
  whitelist:
    - "GET:/foo"
    - "GET:/@vite/client"
    - "GET:/"
    - "POST:/app/getHelloInfo"
  default_user:
    userid: 1
    username: "foo"
    password: "foo123"
    nickname: "奔跑的椰子"

postal:
  smtp_server: "" # SMTP服务器地址
  smtp_port: ""  # SMTP端口(优先465)
  from_email: "" # 发件邮箱
  from_pass: ""  # 发件邮箱密码
  from_name: ""  # 发件人显示名称

attach:
  view_attach_base_url: "http://localhost:6306/public/uploads" # 上传文件访问地址前缀
  upload_dir_path: "./public/uploads" # 上传文件存放目录
  view_large_file_base_url: "http://localhost:6306/public/larges" # 大文件访问地址前缀
  upload_large_file_path: "./public/larges" # 大文件存放目录
  chunk_dir_path: "./public/chunks" # 分片文件存放目录
  chunk_dir_salt: "bluespot_chunk_upload_salt"
